# Generated by Django 4.2.13 on 2026-04-22 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('referrer_bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('referee_bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
    ]
