# Generated by Django 4.2.13 on 2026-05-16 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='converted_at',
            new_name='qualified_at',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referee_bonus_amount',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_bonus_amount',
        ),
        migrations.AddField(
            model_name='referral',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='referral',
            name='rewarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('rewarded', 'Rewarded'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_codes',
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='referrals.referralcode'),
        ),
    ]
