# Generated by Django 4.2.13 on 2026-04-29 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_remove_transaction_transaction_user_id_c72623_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monnify_account_reference', models.CharField(db_index=True, max_length=200, unique=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, default='', max_length=10)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'virtual_accounts',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify'), ('nowpayments', 'NOWPayments')], max_length=20)),
                ('internal_reference', models.CharField(db_index=True, max_length=200, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('payment_url', models.TextField(blank=True, default='')),
                ('payment_address', models.TextField(blank=True, default='')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('original_currency', models.CharField(blank=True, default='', max_length=10)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit', to='wallet.transaction')),
            ],
            options={
                'db_table': 'deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='deposits_user_id_a42880_idx'), models.Index(fields=['provider', 'status'], name='deposits_provide_aa775f_idx'), models.Index(fields=['user', 'created_at'], name='deposits_user_id_730f9d_idx')],
            },
        ),
    ]
