# Generated by Django 4.2.13 on 2026-05-06 19:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_bankaccount_kycdocument_kycprofile_delete_kyc_and_more'),
        ('wallet', '0002_remove_transaction_transaction_user_id_c72623_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review (Admin)'), ('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider', models.CharField(default='paystack', max_length=20)),
                ('provider_recipient_id', models.CharField(blank=True, max_length=100)),
                ('provider_transfer_id', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('reference', models.CharField(db_index=True, max_length=200, unique=True)),
                ('requires_review', models.BooleanField(default=False)),
                ('forced_manual_review', models.BooleanField(default=False, help_text='True if user submitted via manual-review endpoint.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=500)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='kyc.bankaccount')),
                ('debit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_debits', to='wallet.transaction')),
                ('refund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_refunds', to='wallet.transaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawals',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', '-requested_at'], name='withdrawals_user_id_9083fc_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='withdrawals_status_ddef8f_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['provider_transfer_id'], name='withdrawals_provide_905ebb_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='withdrawal_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(check=models.Q(('net_amount__gte', 0)), name='withdrawal_net_amount_non_negative'),
        ),
    ]
