# Generated by Django 4.2.13 on 2026-06-15 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_alter_bankaccount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('withdrawals', '0002_withdrawal_delete_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('TRC20', 'TRON USDT')], db_index=True, default='TRC20', max_length=20)),
                ('address', models.CharField(help_text='Crypto wallet address. TRC-20 addresses are 34 chars starting with T.', max_length=120)),
                ('label', models.CharField(blank=True, default='', help_text="Optional user-supplied label (e.g. 'My Binance wallet').", max_length=50)),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Default wallet for this user — picked automatically if no address specified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive wallets are hidden from selection but kept for audit.')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When this address was first verified. For now: set on save after format validation. Future: small test-transaction confirmation.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crypto_wallets',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='withdrawal',
            name='withdrawal_net_amount_non_negative',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USDT', 'Tether USD')], db_index=True, default='NGN', help_text='Withdrawal currency (NGN for bank, USDT for crypto).', max_length=8),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='network',
            field=models.CharField(blank=True, choices=[('TRC20', 'TRON USDT')], default='', help_text='Crypto network. Empty for bank.', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='rail',
            field=models.CharField(choices=[('bank', 'Bank Transfer (NGN)'), ('crypto', 'Crypto (USDT TRC-20)')], db_index=True, default='bank', help_text='Bank transfer or crypto on-chain.', max_length=10),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='On-chain transaction hash after payout (crypto only).', max_length=120),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, default='', help_text='User crypto wallet (e.g. TRC-20 USDT). Empty for bank.', max_length=120),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Required for bank rail; null for crypto rail.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='kyc.bankaccount'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bank_account__isnull', False), ('rail', 'bank')), models.Q(('rail', 'crypto'), ('wallet_address__gt', '')), _connector='OR'), name='withdrawal_rail_fields_present'),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['user', 'is_active'], name='crypto_wall_user_id_cf0dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['user', 'is_default'], name='crypto_wall_user_id_36ca26_idx'),
        ),
        migrations.AddConstraint(
            model_name='cryptowallet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'network', 'address'), name='unique_active_crypto_wallet_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cryptowallet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('user',), name='one_default_crypto_wallet_per_user'),
        ),
    ]
