# Generated by Django 4.2.13 on 2026-04-22 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streak_day', models.PositiveIntegerField()),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reward_type', models.CharField(choices=[('coin', 'Coin'), ('cash', 'Cash')], default='coin', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_rewards',
                'ordering': ['-claimed_at'],
            },
        ),
    ]
