# Generated by Django 4.2.13 on 2026-05-16 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('spin_count', 'Spin Count'), ('spin_streak', 'Spin Streak'), ('daily_login', 'Daily Login'), ('login_streak', 'Login Streak'), ('referral', 'Referral'), ('deposit', 'Deposit'), ('deposit_streak', 'Deposit Streak'), ('welcome', 'Welcome'), ('win_streak', 'Win Streak'), ('total_staked', 'Total Staked'), ('custom', 'Custom')], max_length=30)),
                ('recurrence', models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('permanent', 'Permanent')], max_length=20)),
                ('criteria', models.JSONField(default=dict)),
                ('reward', models.JSONField(default=dict)),
                ('max_completions_per_user', models.PositiveIntegerField(blank=True, help_text='null = unlimited. 1 = once per window.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True, help_text='False = backend-triggered only, not shown to players.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_number', models.PositiveIntegerField(default=1, help_text='Which completion this is (1st, 2nd, etc.) for challenges with multiple allowed.')),
                ('reward_claimed', models.BooleanField(default=False)),
                ('reward_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_progress',
                'ordering': ['-window_start'],
                'unique_together': {('user', 'challenge', 'window_start')},
            },
        ),
    ]
