# Generated by Django 4.2.13 on 2026-04-27 13:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_c72623_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_08c743_idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_type',
            field=models.CharField(choices=[('coin', 'Coin'), ('cash', 'Cash'), ('staked', 'Staked')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('stake', 'Stake'), ('stake_release', 'Stake Release'), ('stake_forfeit', 'Stake Forfeit'), ('win', 'Win'), ('withdrawal', 'Withdrawal'), ('withdrawal_hold', 'Withdrawal Hold'), ('referral_bonus', 'Referral Bonus'), ('daily_reward', 'Daily Reward'), ('reversal', 'Reversal')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'balance_type', 'status'], name='transaction_user_id_526864_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='transaction_user_id_294647_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('balance_after__gte', 0)), name='wallet_balance_never_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('balance_after', django.db.models.expressions.CombinedExpression(models.F('balance_before'), '+', models.F('amount')))), name='wallet_balance_arithmetic_consistent'),
        ),
    ]
