# Generated by Django 4.2.13 on 2026-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_transaction_transaction_user_id_c72623_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('stake', 'Stake'), ('stake_release', 'Stake Release'), ('stake_forfeit', 'Stake Forfeit'), ('win', 'Win'), ('withdrawal', 'Withdrawal'), ('withdrawal_hold', 'Withdrawal Hold'), ('referral_bonus', 'Referral Bonus'), ('daily_reward', 'Daily Reward'), ('reversal', 'Reversal'), ('refund', 'Refund')], max_length=20),
        ),
    ]
