# Generated by Django 4.2.13 on 2026-06-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_type',
            field=models.CharField(choices=[('deposit_coins', 'Deposit Coins'), ('bonus_coins', 'Bonus Coins'), ('earnings', 'Earnings (NGN)'), ('staked', 'Staked')], max_length=50),
        ),
    ]
