# Generated by Django 4.2.13 on 2026-06-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_balance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USDT', 'Tether USD (TRC-20)')], db_index=True, default='NGN', help_text='Real-world currency this transaction represents.', max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_type',
            field=models.CharField(choices=[('crypto_coins', 'Crypto Coins (USDT)'), ('naira_coins', 'Naira Coins (NGN)'), ('bonus_coins', 'Bonus Coins'), ('crypto_withdraw', 'Crypto Withdraw Balance (USDT)'), ('naira_withdraw', 'Naira Withdraw Balance (NGN)'), ('staked', 'Staked')], max_length=50),
        ),
    ]
