# Generated by Django 4.2.13 on 2026-04-22 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTPOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g. Loss, Small Win, Jackpot', max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=4, help_text='e.g. 0=loss, 0.5=half back, 2=2x, 20=jackpot', max_digits=10)),
                ('probability', models.DecimalField(decimal_places=4, help_text='Percentage probability, e.g. 40.0000 = 40%', max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rtp_outcomes',
                'ordering': ['multiplier'],
            },
        ),
        migrations.CreateModel(
            name='RTPTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('stake_min', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stake_max', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rtp_target', models.DecimalField(blank=True, decimal_places=2, help_text='Informational RTP target. Not enforced.', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rtp_tiers',
                'ordering': ['stake_min'],
            },
        ),
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=15)),
                ('multiplier', models.DecimalField(decimal_places=4, max_digits=10)),
                ('win_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outcome_label', models.CharField(max_length=50)),
                ('rng_value', models.DecimalField(decimal_places=10, max_digits=12)),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spin_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
