# Generated by Django 4.2.13 on 2026-04-29 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_remove_transaction_transaction_user_id_c72623_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('push', 'Push'), ('partial_loss', 'Partial Loss')], max_length=20)),
                ('server_seed', models.CharField(blank=True, max_length=128)),
                ('server_seed_hash', models.CharField(blank=True, max_length=128)),
                ('client_seed', models.CharField(blank=True, max_length=128)),
                ('nonce', models.IntegerField(default=0)),
                ('rng_value', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('reference', models.CharField(db_index=True, max_length=200, unique=True)),
                ('is_welcome_spin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wheel_type', models.CharField(choices=[('standard', 'Standard'), ('power', 'Power'), ('mega', 'Mega'), ('welcome', 'Welcome'), ('daily_challenge', 'Daily Challenge')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('currency_type', models.CharField(choices=[('coin', 'Coin'), ('cash', 'Cash')], default='coin', max_length=10)),
                ('min_stake', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_stake', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_welcome_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rtp_target', models.DecimalField(blank=True, decimal_places=2, help_text='Informational target RTP percentage. Not enforced.', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wheels',
                'ordering': ['min_stake'],
            },
        ),
        migrations.CreateModel(
            name='WheelSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('label', models.CharField(help_text='User-visible label, e.g. "Loss", "₦1000", "10x"', max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=4, help_text='0=loss, 1=push (stake back), 2+=win', max_digits=10)),
                ('probability_weight', models.PositiveIntegerField(help_text='Integer weight relative to other segments on this wheel.')),
                ('color', models.CharField(blank=True, default='', help_text='Hex color for client animation, e.g. "#C9961A"', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='spin.wheel')),
            ],
            options={
                'db_table': 'wheel_segments',
                'ordering': ['wheel', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='wheel',
            constraint=models.CheckConstraint(check=models.Q(('max_stake__gte', models.F('min_stake'))), name='wheel_max_stake_gte_min'),
        ),
        migrations.AddField(
            model_name='spin',
            name='lock_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spin_locks', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='spin',
            name='resolution_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spin_resolutions', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='spin',
            name='segment_landed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='spin.wheelsegment'),
        ),
        migrations.AddField(
            model_name='spin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spin',
            name='wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='spin.wheel'),
        ),
        migrations.AddConstraint(
            model_name='wheelsegment',
            constraint=models.CheckConstraint(check=models.Q(('probability_weight__gte', 0)), name='segment_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wheelsegment',
            constraint=models.CheckConstraint(check=models.Q(('multiplier__gte', 0)), name='segment_multiplier_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wheelsegment',
            constraint=models.UniqueConstraint(fields=('wheel', 'position'), name='unique_segment_position_per_wheel'),
        ),
        migrations.AddIndex(
            model_name='spin',
            index=models.Index(fields=['user', '-created_at'], name='spins_user_id_27465e_idx'),
        ),
        migrations.AddIndex(
            model_name='spin',
            index=models.Index(fields=['wheel', '-created_at'], name='spins_wheel_i_7e3369_idx'),
        ),
        migrations.AddIndex(
            model_name='spin',
            index=models.Index(fields=['outcome'], name='spins_outcome_73361f_idx'),
        ),
        migrations.AddConstraint(
            model_name='spin',
            constraint=models.UniqueConstraint(condition=models.Q(('is_welcome_spin', True)), fields=('user',), name='one_welcome_spin_per_user'),
        ),
    ]
