# Generated by Django 4.2.13 on 2026-06-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spin',
            name='source_wallet',
            field=models.CharField(choices=[('deposit_coins', 'Deposit Coins'), ('bonus_coins', 'Bonus Coins')], db_index=True, default='deposit_coins', help_text='Which coin balance funded this spin. Determines payout rules.', max_length=20),
        ),
    ]
