# Generated by Django 4.2.13 on 2026-04-22 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        ('spin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spinresult',
            name='stake_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spin_stake', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='spinresult',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_results', to='spin.rtptier'),
        ),
        migrations.AddField(
            model_name='spinresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spinresult',
            name='win_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_win', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='rtptier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rtpoutcome',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='spin.rtptier'),
        ),
    ]
