# Generated by Django 4.2.13 on 2026-06-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0002_spin_source_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='spin',
            name='bonus_destination',
            field=models.CharField(blank=True, choices=[('crypto', 'Crypto Withdraw Balance'), ('naira', 'Naira Withdraw Balance')], default='', help_text='Which withdraw balance bonus wins should be credited to. Required only when source_wallet=bonus_coins. Empty string for non-bonus spins.', max_length=10),
        ),
        migrations.AddField(
            model_name='spin',
            name='credited_balance',
            field=models.CharField(blank=True, choices=[('', 'N/A (loss)'), ('crypto_withdraw', 'Crypto Withdraw Balance'), ('naira_withdraw', 'Naira Withdraw Balance'), ('naira_coins', 'Naira Coins (push refund)'), ('crypto_coins', 'Crypto Coins (push refund)'), ('bonus_coins', 'Bonus Coins (push refund)')], default='', help_text='Where the payout was credited. For wins: a withdraw balance. For pushes: the origin coin bucket. Empty for losses.', max_length=20),
        ),
        migrations.AddField(
            model_name='spin',
            name='payout_currency',
            field=models.CharField(blank=True, choices=[('', 'N/A (loss)'), ('NGN', 'Naira'), ('USDT', 'USDT')], default='', help_text='Real-world currency credited on a win. Empty for losses.', max_length=8),
        ),
        migrations.AlterField(
            model_name='spin',
            name='source_wallet',
            field=models.CharField(choices=[('crypto_coins', 'Crypto Coins'), ('naira_coins', 'Naira Coins'), ('bonus_coins', 'Bonus Coins')], db_index=True, default='naira_coins', help_text='Which coin balance funded this spin. Determines payout rules.', max_length=20),
        ),
    ]
