# Generated by Django 4.2.13 on 2026-06-16 07:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0003_spin_bonus_destination_spin_credited_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spin',
            name='net_credited',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Actual amount credited to credited_balance. For wins/partials on bonus spins, this is the bonus-adjusted net (gross × bonus_payout_rate × conversion_rate). For naira/crypto wins, this equals payout_amount (100% rate). For pushes, this is the stake refunded. For losses, 0.', max_digits=20),
        ),
    ]
