# Generated by Django 4.2.13 on 2026-05-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAuditLog',
        ),
    ]
