# Generated by Django 4.2.13 on 2026-05-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('finance_admin', 'Finance Admin'), ('support_admin', 'Support Admin'), ('risk_admin', 'Risk Admin'), ('read_only', 'Read Only')], db_index=True, default='read_only', help_text='Determines which admin actions are permitted.', max_length=20),
        ),
    ]
