# Generated by Django 4.2.13 on 2026-04-22 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('nin_encrypted', models.TextField()),
                ('dob', models.DateField()),
                ('bank_account', models.CharField(max_length=20)),
                ('bank_code', models.CharField(max_length=10)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('document_url', models.TextField(blank=True)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC Records',
                'db_table': 'kyc',
            },
        ),
    ]
