# Generated by Django 4.2.13 on 2026-05-05 10:55

import apps.kyc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_accounts',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.kyc.models.kyc_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement')], default='utility_bill', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='False if superseded by a newer upload.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('nin', apps.kyc.models.EncryptedField(blank=True)),
                ('bvn', apps.kyc.models.EncryptedField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('personal_info_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_correction', 'Requires Correction')], default='pending', max_length=25)),
                ('bank_account_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_correction', 'Requires Correction')], default='pending', max_length=25)),
                ('document_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_correction', 'Requires Correction')], default='pending', max_length=25)),
                ('personal_info_reason', models.CharField(blank=True, max_length=500)),
                ('bank_account_reason', models.CharField(blank=True, max_length=500)),
                ('document_reason', models.CharField(blank=True, max_length=500)),
                ('nin_lookup_response', models.JSONField(blank=True, default=dict)),
                ('bvn_lookup_response', models.JSONField(blank=True, default=dict)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_resubmission_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='KYC',
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='one_active_bank_account_per_user'),
        ),
    ]
