# Generated by Django 4.2.13 on 2026-05-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_bankaccount_kycdocument_kycprofile_delete_kyc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='one_active_bank_account_per_user',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Most recently used account. Auto-managed.'),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='nin_full_name',
            field=models.CharField(blank=True, help_text='Full name as returned by the NIN verification provider.', max_length=200),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(help_text='Name returned by the bank account resolver — matched against NIN name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag. False = removed by user.'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the bank name was successfully matched against NIN.', null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='content_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], default='utility_bill', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='file',
            field=models.FileField(upload_to='kyc/documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='file_size_bytes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='bank_account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_correction', 'Requires Correction')], default='pending', help_text='DEPRECATED — bank verification moved to withdrawal time.', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'bank_code', 'account_number'), name='unique_active_bank_account'),
        ),
    ]
